version: "3.9"
services:
  backend:
    build: .
    container_name: "city_api"
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: "city_db"
    image: "postgis/postgis:13-master"
    volumes:
      - citygame-pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  citygame-pgdata:
