# Generated by Django 3.2.8 on 2021-10-11 19:53

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('img', models.ImageField(upload_to='media/')),
                ('is_live', models.BooleanField(default=False)),
                ('is_close', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='media/')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('importance', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_date', models.DateTimeField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questtype')),
            ],
        ),
    ]
