# Generated by Django 3.2.8 on 2021-10-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questtype',
            name='img',
            field=models.ImageField(default='media/Sosnowiec_Ez9aS4C.jpg', upload_to='media/'),
            preserve_default=False,
        ),
    ]
