# Generated by Django 3.2.8 on 2021-10-10 04:30

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_questtype_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
